[project]
name = "iptv-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "m3u-parser>=0.4.2",
    "polars>=1.38.1",
    "typer>=0.24.1",
]
